apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-5yy3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-5yy3
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-5yy3
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-5yy3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-5yy3
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-pshj-tenant/rhtap-demo-app/hacbs-test-project-5yy3@sha256:e47fd09691137c05872fe22a035e3a476295bce8691d9d2f27a651bc7d556eff
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
